In [1]:
import numpy as np
f = np.arange(1, 2, 0.3, dtype=float)

In [9]:
type(f)


numpy.ndarray

In [3]:
c = np.array([False, False, True])

In [8]:
print c
type(c)

[False False  True]


numpy.ndarray

In [7]:
b = np.array([1, 2, 3, 4, 5], dtype=float)
print b
type(b)

[ 1.  2.  3.  4.  5.]


numpy.ndarray

In [6]:
type(b)

numpy.ndarray

In [10]:
b = np.array(1, 2, 3, 4, 5, dtype=float)
print b
type(b)

ValueError: only 2 non-keyword arguments accepted

In [11]:
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])


In [12]:
import scipy
scipy.spatial.distance.cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')

AttributeError: 'module' object has no attribute 'spatial'

In [13]:
scipy.spatial.distance.cdist(a[:, np.newaxis], b[:, np.newaxis], metric='euclidean')

AttributeError: 'module' object has no attribute 'spatial'

In [14]:
np.linalg.norm(a, ord=2) - np.linalg.norm(b, ord=2)

1.2955324534752801

In [15]:
scipy.spatial.distance.cdist(b, a, metric='euclidean')

AttributeError: 'module' object has no attribute 'spatial'

In [16]:
import scipy

In [17]:
scipy.spatial.distance.cdist(b, a, metric='euclidean')

AttributeError: 'module' object has no attribute 'spatial'

In [21]:
a = np.array([8, 10, -1, 0, 0])
a = a[:, np.newaxis]
print a

[[ 8]
 [10]
 [-1]
 [ 0]
 [ 0]]


In [19]:
a


array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])